name: my_project
version: 0.0.1
description: project
environment:
  skd: '>=1.13.0 <2.0.0'
dependencies:
  angular2:
  bootstrap_sass:
  browser:
  dart_to_js_script_rewriter:
  font_awesome:
  http:
  mongo_dart:
  ng2_strap:
  path: '>=1.3.5 <1.4.0'
  redstone: '>=0.5.21 <0.6.0'
  sass:
  shelf_static: '>=0.2.2 <0.3.0'
transformers:
- angular2:
    resolved_identifiers:
      BrowserClient: 'package:http/browser_client.dart'
    platform_directives:
    - 'package:angular2/common.dart#COMMON_DIRECTIVES'
    platform_pipes:
    - 'package:angular2/common.dart#COMMON_PIPES'
    entry_points: web/main.dart
- dart_to_js_script_rewriter
- sass
